name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          api-level: 30
          ndk: "22.1.7171670"

      - name: Build Android
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Install Cocoapods
        run: |
          sudo gem install cocoapods
          cd ios && pod install

      - name: Build iOS
        run: |
          xcodebuild -workspace ios/YourProjectName.xcworkspace \
            -scheme YourProjectName \
            -sdk iphonesimulator \
            -configuration Release \
            -derivedDataPath build

      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build
